### ISSUE TITLE
Upstream Proxy

### ISSUE THREAD

**Issue by adamtimmins** [PortSwigger/turbo-intruder#11]
Is there anyway to get Turbo Intruder to go through the upstream proxy configuration? 

Everytime I run the tool with this configured all I can see in the logs are thread connection failures. 

Cheers,

**Comment by albinowax** [comment]
Turbo Intruder uses its own network stack by default which doesn't support upstream proxies. I don't plan to ever code support for this because proxies remove most of the speed benefits anyway.

That said, you can make turbo intruder use burp's network stack by adding engine=Engine.BURP to the RequestEngine constructor in your python snippet.

**Comment by adamtimmins** [comment]
Thanks James this works,

Keep up the great work!
👍

**Comment by putravenkataraju164** [comment]
https://github.com/PortSwigger/turbo-intruder/blob/master/resources/examples/burpIntegration.py

**Comment by joyas11** [comment]
> On further reflection, it looks like adding SOCKS support for the Threaded engine is fairly simple so I will tackle this at some point

how

**Comment by MujurID** [comment]
> On further reflection, it looks like adding SOCKS support for the Threaded engine is fairly simple so I will tackle this at some point

Turbo Intruder respects Burp's proxy settings when using Engine.BURP and Engine.BURP2, but when using Engine.THREADED and Engine.HTTP2 it doesn't respect System's proxy settings, @albinowax  how can I use proxy on those engines?
It would be great if could manually configure the proxy in the "engine.queue()" section.
