### ISSUE TITLE
Turbo Intruder modify requst body

### ISSUE THREAD

**Issue by PvlFn** [PortSwigger/turbo-intruder#92]
Hello!

My POST-request contains rpm-file. This request successfully sends via GUI Turbo Intruder.
Then I save requet to file, using "Copy to file" in context menu:

![Context menu](https://user-images.githubusercontent.com/89650763/147753057-6c61b7a6-0f67-4a32-867e-2c24f01f86a4.png)

And when try send request via CLI Turbo Intruder, but I get unsuccessful response with error "Invalide rpm-file" (400 error code in response):

![cli turbo intruder run](https://user-images.githubusercontent.com/89650763/147753276-dec861c9-5ac4-4529-b0f6-17f6839ddef9.png)

I intercepted this two request with using Wireshark and compared them. The files contains differences:
![2021-12-30 DiffRequestsBody](https://user-images.githubusercontent.com/89650763/147750644-d927f024-1389-4e7c-886f-5813cf89a41e.png)

Why CLI Turbo Intruder modify request and make it incorrect? Can you help me with this problem?

Thank you!

**Comment by shafouz** [comment]
I think if your request has non ascii characters you get those question mark artifacts. Im not sure why you could try ctrl+c ctrl+v instead of save to file that might work. Another option is to url encode all the non ascii characters save to file and decode, so \00 to %00, etc. You could use a tool like https://gchq.github.io/CyberChef/ it might work.

**Comment by albinowax** [comment]
I believe this has since been fixed.
